import type { Metadata, Viewport } from "next";
import "./globals.css";

import { AuthSignedOutRedirect } from "@/components/AuthSignedOutRedirect";
import { OfflineIndicator } from "@/components/OfflineIndicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5, // Allow pinch zoom for accessibility
  userScalable: true,
  viewportFit: "cover", // iOS safe area support
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <OfflineIndicator />
        <AuthSignedOutRedirect />
        {children}
      </body>
    </html>
  );
}
