import type { Metadata } from "next";
import "./globals.css";

import { AuthSignedOutRedirect } from "@/components/AuthSignedOutRedirect";
import { OfflineIndicator } from "@/components/OfflineIndicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <OfflineIndicator />
        <AuthSignedOutRedirect />
        {children}
      </body>
    </html>
  );
}
