// lib/seed/teamsSeed.ts
import type { Team } from "@/types";

/**
 * World Cup 2026 groups (as provided) + placeholders.
 * Source context: Dec 5, 2025 draw reporting. :contentReference[oaicite:1]{index=1}
 */
export const TEAMS_SEED: Team[] = [
  // Group A
  {
    id: "MEX",
    name: "Mexico",
    group: "A",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/mx.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "KOR",
    name: "South Korea",
    group: "A",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/kr.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "ZAF",
    name: "South Africa",
    group: "A",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/za.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "PO_UE_D",
    name: "Winner UEFA Play-off D",
    group: "A",
    tier: 4,
    flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group B
  {
    id: "CAN",
    name: "Canada",
    group: "B",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/ca.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "SUI",
    name: "Switzerland",
    group: "B",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/ch.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "QAT",
    name: "Qatar",
    group: "B",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/qa.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "PO_UE_A",
    name: "Winner UEFA Play-off A",
    group: "B",
    tier: 4,
    flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group C
  {
    id: "BRA",
    name: "Brazil",
    group: "C",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/br.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "MAR",
    name: "Morocco",
    group: "C",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/ma.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "SCO",
    name: "Scotland",
    group: "C",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/gb-sct.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "HTI",
    name: "Haiti",
    group: "C",
    tier: 4,
    flagUrl: "https://flagcdn.com/w320/ht.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group D
  {
    id: "USA",
    name: "USA",
    group: "D",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/us.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "AUS",
    name: "Australia",
    group: "D",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/au.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "PRY",
    name: "Paraguay",
    group: "D",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/py.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "PO_UE_C",
    name: "Winner UEFA Play-off C",
    group: "D",
    tier: 4,
    flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group E
  {
    id: "GER",
    name: "Germany",
    group: "E",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/de.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "ECU",
    name: "Ecuador",
    group: "E",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/ec.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "CIV",
    name: "Ivory Coast",
    group: "E",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/ci.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "CUW",
    name: "Curaçao",
    group: "E",
    tier: 4,
    flagUrl: "https://flagcdn.com/w320/cw.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group F
  {
    id: "NED",
    name: "Netherlands",
    group: "F",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/nl.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "JPN",
    name: "Japan",
    group: "F",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/jp.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "TUN",
    name: "Tunisia",
    group: "F",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/tn.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "PO_UE_B",
    name: "Winner UEFA Play-off B",
    group: "F",
    tier: 4,
    flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group G
  {
    id: "BEL",
    name: "Belgium",
    group: "G",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/be.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "IRN",
    name: "Iran",
    group: "G",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/ir.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "EGY",
    name: "Egypt",
    group: "G",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/eg.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "NZL",
    name: "New Zealand",
    group: "G",
    tier: 4,
    flagUrl: "https://flagcdn.com/w320/nz.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group H
  {
    id: "ESP",
    name: "Spain",
    group: "H",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/es.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "URU",
    name: "Uruguay",
    group: "H",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/uy.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "KSA",
    name: "Saudi Arabia",
    group: "H",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/sa.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "CPV",
    name: "Cabo Verde",
    group: "H",
    tier: 4,
    flagUrl: "https://flagcdn.com/w320/cv.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group I
  {
    id: "FRA",
    name: "France",
    group: "I",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/fr.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "SEN",
    name: "Senegal",
    group: "I",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/sn.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "NOR",
    name: "Norway",
    group: "I",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/no.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "PO_FIFA_2",
    name: "Winner FIFA PO-2",
    group: "I",
    tier: 4,
    flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/FIFA_flag_2010.svg",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group J
  {
    id: "ARG",
    name: "Argentina",
    group: "J",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/ar.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "AUT",
    name: "Austria",
    group: "J",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/at.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "DZA",
    name: "Algeria",
    group: "J",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/dz.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "JOR",
    name: "Jordan",
    group: "J",
    tier: 4,
    flagUrl: "https://flagcdn.com/w320/jo.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group K
  {
    id: "POR",
    name: "Portugal",
    group: "K",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/pt.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "COL",
    name: "Colombia",
    group: "K",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/co.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "UZB",
    name: "Uzbekistan",
    group: "K",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/uz.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "PO_FIFA_1",
    name: "Winner FIFA PO-1",
    group: "K",
    tier: 4,
    flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/FIFA_flag_2010.svg",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },

  // Group L
  {
    id: "ENG",
    name: "England",
    group: "L",
    tier: 1,
    flagUrl: "https://flagcdn.com/w320/gb-eng.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "HRV",
    name: "Croatia",
    group: "L",
    tier: 2,
    flagUrl: "https://flagcdn.com/w320/hr.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "PAN",
    name: "Panama",
    group: "L",
    tier: 3,
    flagUrl: "https://flagcdn.com/w320/pa.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
  {
    id: "GHA",
    name: "Ghana",
    group: "L",
    tier: 4,
    flagUrl: "https://flagcdn.com/w320/gh.png",
    isEliminated: false,
    wins: 0, draws: 0, goalsScored: 0, goalsConceded: 0,
    cleanSheets: 0, redCards: 0, yellowCards: 0,
  },
];
